#!/bin/sh

PROJECTS="msm8226_moneypenny msm8226_tesla msm8226_dempsey"
FAILED=""

for p in $PROJECTS; do
	PROJECT=$p make -j2 || FAILED="$FAILED $p"
done

if [ "$FAILED" != "" ]; then
	echo
	echo some projects have failed to build:
	echo $FAILED
fi
